language: "php"

php:
 # - 5.3
 # - 5.4
 # - 5.5
 # - 5.6
  - 7.0
 # - hhvm

before_script: 
- "composer require codeclimate/php-test-reporter --dev"
- "composer install"

script: 
- "phpunit"

after_script:
- CODECLIMATE_REPO_TOKEN="0376dd23cbdb8d03794a8b681edec076efc77f267d125134cbad4d74eb010b40" vendor/bin/test-reporter --stdout > codeclimate.json
- "sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -d @codeclimate.json -H \"Content-Type: application/json\" -H \"User-Agent: Code Climate (PHP Test Reporter v0.1.1)\" https://codeclimate.com/test_reports  ; fi'"
